apiVersion: apps/v1
kind: Deployment

metadata:
  name: flask-deployment

spec: 
  replicas: 5
  selector: 
     matchLabels: 
       app: flask

  template: 
    metadata: 
      labels: 
       app: flask
    spec: 
      containers:
      - name: flask-container
        image: richa111/flask-app:latest
        ports: 
        - containerPort: 5000
